#!/bin/bash

# this script installs WSRemoteGPIO v3.0 following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/WSRemoteGPIO/current"

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates

packageGitHubUser="tempesta-home"
packageGitHubBranch="main"


#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "The WSRemoteGPIO is adding external Relays and Digital Inputs"
	echo "with Dingtian IOT Relay devices either connected via USB or TCP"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing WSRemoteGPIO"

	##
	## Prepare the devices in /data/WSRemoteGPIO/sys and conf folder
	##############################################################
	tar -xvf /data/WSRemoteGPIO/FileSets/VersionIndependent/sys.tar.gz -C /data/WSRemoteGPIO/
	tar -xvf /data/WSRemoteGPIO/FileSets/VersionIndependent/bin.tar.gz -C /data/WSRemoteGPIO/
	mkdir /data/WSRemoteGPIO/conf
	chmod 777 /data/WSRemoteGPIO/conf
	touch /data/WSRemoteGPIO/conf/relays.conf
	chmod 666 /data/WSRemoteGPIO/conf/relays.conf
	echo "0" > /data/WSRemoteGPIO/conf/relays.conf
	mkdir /var/log/WSRemoteGPIO

	
	##
	## For Large Image only with Node-Red support
	#############################################
	if [ $(dbus -y com.victronenergy.settings /Settings/System/ImageType GetValue) == 1 ]
	then

		if [ ! -f /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json.orig ]
		then
		cp /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json.orig
		fi
		patch /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json /data/WSRemoteGPIO/FileSets/PatchSource/services.json.patch
		
	fi
	
	##
	## For supports of Cerbo GX MK2
	###############################
	patch /opt/victronenergy/dbus-digitalinputs/start-digitalinputs.sh /data/WSRemoteGPIO/FileSets/PatchSource/start-digitalinputs.sh.patch


	logMessage "++ $packageName installed"
fi


# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling WSRemoteGPIO"



	##
	## For Large Image only with Node-Red support
	#############################################
	if [ $(dbus -y com.victronenergy.settings /Settings/System/ImageType GetValue) == 1 ]
	then
		patch -R /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json /data/WSRemoteGPIO/FileSets/PatchSource/services.json.patch
		
	fi


	##
	## Delete devices
	#################	
	rm -f /dev/gpio/relay_3
	rm -f /dev/gpio/relay_4
	rm -f /dev/gpio/relay_5
	rm -f /dev/gpio/relay_6
	rm -f /dev/gpio/relay_7
	rm -f /dev/gpio/relay_8
	rm -f /dev/gpio/relay_9
	rm -f /dev/gpio/relay_a
	rm -f /dev/gpio/relay_b
	rm -f /dev/gpio/relay_c
	rm -f /dev/gpio/relay_d
	rm -f /dev/gpio/relay_e
	rm -f /dev/gpio/relay_f
	rm -f /dev/gpio/relay_g
	rm -f /dev/gpio/relay_h
	rm -f /dev/gpio/relay_i
	rm -f /dev/gpio/digital_input_5
	rm -f /dev/gpio/digital_input_6
	rm -f /dev/gpio/digital_input_7
	rm -f /dev/gpio/digital_input_8
	rm -f /dev/gpio/digital_input_9
	rm -f /dev/gpio/digital_input_a
	rm -f /dev/gpio/digital_input_b
	rm -f /dev/gpio/digital_input_c
	rm -f /dev/gpio/digital_input_d
	rm -f /dev/gpio/digital_input_e
	rm -f /dev/gpio/digital_input_f
	rm -f /dev/gpio/digital_input_g
	rm -f /dev/gpio/digital_input_h
	rm -f /dev/gpio/digital_input_i
	rm -f /dev/gpio/digital_input_j
	rm -f /dev/gpio/digital_input_k
	
	rm -Rf /data/WSRemoteGPIO/conf
	
	
		
	logMessage "++ $packageName uninstalled"
fi


	svc -t /service/dbus-digitalinputs

logMessage "completed"
	
# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript INSTALL_FILES ADD_DBUS_SETTINGS INSTALL_SERVICES